#!/bin/bash
# /etc/init.d/updatetool

### BEGIN INIT INFO
# Provides:          updatetool
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: geekHOME Update Tool
# Description:       This service is used to manage a GeekHOME Update Tool
### END INIT INFO


case "$1" in 
    start)
        echo "Starting updatetool"
        cd /home/pi/geekhome
        java -Dfile.encoding=UTF-8 -cp "/home/pi/geekhome/updatebin/*" com.updatetool.Main
        ;;
    stop)
        echo "Stopping updatetool"
        killall updatetool
        ;;
    *)
        echo "Usage: /etc/init.d/updatetool start|stop"
        exit 1
        ;;
esac

exit 0