#!/bin/bash
# /etc/init.d/geekhome

### BEGIN INIT INFO
# Provides:          geekhome
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: geekHOME server
# Description:       This service is used to manage GeekHOME Server
### END INIT INFO


case "$1" in 
    start)
        echo "Starting geekhome"
        cd /home/pi/geekhome
        java -Dfile.encoding=UTF-8 -Dlog4j.configurationFile=/home/pi/geekhome/log4j2.xml -Djava.library.path=/usr/lib/jni -jar final-geekhome-all.jar
        ;;
    stop)
        echo "Stopping geekhome"
        killall geekhome
        ;;
    *)
        echo "Usage: /etc/init.d/geekhome start|stop"
        exit 1
        ;;
esac

exit 0